### ISSUE TITLE
Request for sharing intermediate files

### ISSUE THREAD

**Issue by Junna-Kawasaki** [cednotsed/vertebrate_host_jumps#2]
Can you please publish an intermediate file (rooted treefile) corresponding to the {clique_name}.anc_recon.pdf published on zenodo?

**Comment by cednotsed** [comment]
Hi, thanks for your interest in the analysis. I have now published the newick files of the trees as requested (https://zenodo.org/records/12606377).

Tip labels are formatted as {genbank accession}|{host}|{collection_date}|{country}.

Nodel labels are formatted as follows:

1. rooted_trees_simplified: {node name}|{host}, where {host} is the most likely ancestral state (i.e., highest ancestral state likelihood)
2. rooted_trees: {node name}|{host1}:{likelihood1}|{host2}:{likelihood2}...|{hostn}:{likelihoodn}, which provides the raw ancestral state likelihoods for each host state. 
A

All node names correspond to those provided in the Supplementary Tables in Tan et al. 2024.

Note that the ancestral state reconstructions were performed on the trees using host names provided in the GenBank metadata, which included taxa resolved at various ranks (e.g. Camelus, Camelus dromedarius, Artiodactyla). Inferring host jumps using this information is tricky because a state transition from Camelus->Camelus dromedarius may or may not represent a host jump. To deal with this, if the ancestral host states in a candidate host transition were of different ranks, both host state of lower rank must not be a member of the higher rank. For example, Camelus->Camelus dromedarius is not considered a host jump, whereas Felis catus->Primates would be considered a host jump. 

Another point to note is that the ancestral host states provided in 'rooted_trees_simplified' are the most likely ancestral states, which in some cases are associated with a great deal of uncertainty (i.e., one or more host states have similar likelihoods). In our analysis, we used an arbitrary rule of retaining only host state transitions where the most likely host state is twice that of any other state to exclude these uncertain host transitions. I strongly recommend considering the ancestral state likelihoods in a similar fashion for your analysis. 

Please let me know if you need any further help, you can contact me at `cedriccstan@gmail.com` if necessary. Closing this issue for now.
